name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build-app.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: pebble-app

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.pbw'
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
